// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Textsecure
{
    public partial class SessionStructure
    {
        public uint SessionVersion { get; set; }

        public byte[] LocalIdentityPublic { get; set; }

        public byte[] RemoteIdentityPublic { get; set; }

        public byte[] RootKey { get; set; }

        public uint PreviousCounter { get; set; }

        public Textsecure.SessionStructure.Chain SenderChain { get; set; }

        public List<Textsecure.SessionStructure.Chain> ReceiverChains { get; set; }

        public Textsecure.SessionStructure.PendingKeyExchange PendingKeyExchangeField { get; set; }

        public Textsecure.SessionStructure.PendingPreKey PendingPreKeyField { get; set; }

        public uint RemoteRegistrationId { get; set; }

        public uint LocalRegistrationId { get; set; }

        public bool NeedsRefresh { get; set; }

        public byte[] AliceBaseKey { get; set; }

        public partial class Chain
        {
            public byte[] SenderRatchetKey { get; set; }

            public byte[] SenderRatchetKeyPrivate { get; set; }

            public Textsecure.SessionStructure.Chain.ChainKey ChainKeyField { get; set; }

            public List<Textsecure.SessionStructure.Chain.MessageKey> MessageKeys { get; set; }

            public partial class ChainKey
            {
				public uint Index { get; set; }

                public byte[] Key { get; set; }

            }

            public partial class MessageKey
            {
                public uint Index { get; set; }

                public byte[] CipherKey { get; set; }

                public byte[] MacKey { get; set; }

                public byte[] Iv { get; set; }

            }

        }

        public partial class PendingKeyExchange
        {
            public uint Sequence { get; set; }

            public byte[] LocalBaseKey { get; set; }

            public byte[] LocalBaseKeyPrivate { get; set; }

            public byte[] LocalRatchetKey { get; set; }

            public byte[] LocalRatchetKeyPrivate { get; set; }

            public byte[] LocalIdentityKey { get; set; }

            public byte[] LocalIdentityKeyPrivate { get; set; }

        }

        public partial class PendingPreKey
        {
            public uint PreKeyId { get; set; }

            public int SignedPreKeyId { get; set; }

            public byte[] BaseKey { get; set; }

        }
		
    }

    public partial class RecordStructure
    {
        public Textsecure.SessionStructure CurrentSession { get; set; }

        public List<Textsecure.SessionStructure> PreviousSessions { get; set; }

    }

    public partial class PreKeyRecordStructure
    {
        public uint Id { get; set; }

        public byte[] PublicKey { get; set; }

        public byte[] PrivateKey { get; set; }

    }

    public partial class SignedPreKeyRecordStructure
    {
        public uint Id { get; set; }

        public byte[] PublicKey { get; set; }

        public byte[] PrivateKey { get; set; }

        public byte[] Signature { get; set; }

        public ulong Timestamp { get; set; }

    }

    public partial class IdentityKeyPairStructure
    {
        public byte[] PublicKey { get; set; }

        public byte[] PrivateKey { get; set; }

    }

    public partial class SenderKeyStateStructure
    {
        public uint SenderKeyId { get; set; }

        public Textsecure.SenderKeyStateStructure.SenderChainKey SenderChainKeyField { get; set; }

        public Textsecure.SenderKeyStateStructure.SenderSigningKey SenderSigningKeyField { get; set; }

        public List<Textsecure.SenderKeyStateStructure.SenderMessageKey> SenderMessageKeys { get; set; }

        public partial class SenderChainKey
        {
            public uint Iteration { get; set; }

            public byte[] Seed { get; set; }

        }

        public partial class SenderMessageKey
        {
            public uint Iteration { get; set; }

            public byte[] Seed { get; set; }

        }

        public partial class SenderSigningKey
        {
            public byte[] Public { get; set; }

            public byte[] Private { get; set; }

        }

    }

    public partial class SenderKeyRecordStructure
    {
        public List<Textsecure.SenderKeyStateStructure> SenderKeyStates { get; set; }

    }

}
